language: node_js

env:
  - DATABASE_URL=postgresql://coder:pg123@localhost:5432/users

node_js:  
  - "12.18.3"

before_script:
  - psql -c 'create database  users' -U postgres
  - psql -U postgres -d users -a -f users.sql

services:
  - postgresql
